/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chris022.dagger.tutorial

import chris022.dagger.tutorial.CoffeeShop

fun main() {
    var coffeeShop: CoffeeShop = DaggerCoffeeShop.create();
    var coffee = coffeeShop.brew();
    coffee.drink();
}
